# Generated by Django 3.0.5 on 2020-04-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default=1, upload_to='blog_post/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
